#!/usr/bin/env bash
# Container start-up: make sure the instance has stable secrets, bring the
# database schema up to date, then hand over to supervisord.
set -euo pipefail

DATA_DIR="${DATA_DIR:-/app/backend/data}"
BACKEND_DIR="/app/backend"
SECRETS_FILE="${DATA_DIR}/.secrets.env"

log() { printf '[entrypoint] %s\n' "$*"; }
fail() { printf '[entrypoint] ERROR: %s\n' "$*" >&2; }

mkdir -p "${DATA_DIR}"

# ---------------------------------------------------------------------------
# Secrets
# ---------------------------------------------------------------------------
# SECRET_KEY signs the JWTs; ENCRYPTION_KEY derives the key that encrypts the
# stored LinkedIn session. Both must survive restarts: a new SECRET_KEY logs
# everyone out, and a new ENCRYPTION_KEY makes the saved session unreadable.
# When they are not supplied through the environment we generate them once and
# persist them on the data volume.
if [[ -f "${SECRETS_FILE}" ]]; then
    # shellcheck disable=SC1090
    set -a && source "${SECRETS_FILE}" && set +a
fi

generate_key() {
    python3 -c "import secrets; print(secrets.token_urlsafe(48))"
}

generated=0
if [[ -z "${SECRET_KEY:-}" ]]; then
    SECRET_KEY="$(generate_key)"
    export SECRET_KEY
    generated=1
    log "generated a new SECRET_KEY"
fi
if [[ -z "${ENCRYPTION_KEY:-}" ]]; then
    ENCRYPTION_KEY="$(generate_key)"
    export ENCRYPTION_KEY
    generated=1
    log "generated a new ENCRYPTION_KEY"
fi

if [[ "${generated}" -eq 1 ]]; then
    umask 077
    {
        printf '# Generated by docker/entrypoint.sh on first start.\n'
        printf '# Keep this file. Deleting it logs every user out and makes the\n'
        printf '# stored LinkedIn session permanently unreadable.\n'
        printf 'SECRET_KEY=%s\n' "${SECRET_KEY}"
        printf 'ENCRYPTION_KEY=%s\n' "${ENCRYPTION_KEY}"
    } > "${SECRETS_FILE}"
    chmod 600 "${SECRETS_FILE}"
    log "persisted secrets to ${SECRETS_FILE}"
fi

# ---------------------------------------------------------------------------
# AI key
# ---------------------------------------------------------------------------
# Missing key is loud but not fatal: the UI has to come up so you can set up an
# account and paste the key into .env without fighting a crash loop.
if [[ -z "${ANTHROPIC_API_KEY:-}" ]]; then
    fail "ANTHROPIC_API_KEY is not set."
    fail "Job scoring, screening answers and cover letters will be unavailable."
    fail "Add it to your .env file and restart:  ANTHROPIC_API_KEY=sk-ant-..."
    fail "Get a key at https://console.anthropic.com/"
fi

# ---------------------------------------------------------------------------
# Database schema
# ---------------------------------------------------------------------------
cd "${BACKEND_DIR}"
log "applying database migrations"
if alembic -c "${BACKEND_DIR}/alembic.ini" upgrade head; then
    log "database is up to date"
else
    fail "alembic upgrade failed; falling back to create-missing-tables."
    fail "Existing data is left untouched, but run 'alembic upgrade head'"
    fail "manually to find out what went wrong."
    python3 -c "import asyncio; from app.database.session import init_models; asyncio.run(init_models())"
    log "schema created via init_models()"
fi

# ---------------------------------------------------------------------------
# Hand over
# ---------------------------------------------------------------------------
log "application:  http://localhost:8000"
log "browser view: http://localhost:6080  (log in to LinkedIn here)"

exec supervisord -c /etc/supervisor/supervisord.conf
